In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report

In [2]:
'''f1=pd.read_csv('/content/processed_sensor_data_FD001.csv')
f2=pd.read_csv('/content/processed_sensor_data_FD002.csv')
f3=pd.read_csv('/content/processed_sensor_data_FD003.csv')
f4=pd.read_csv('/content/processed_sensor_data_FD004.csv')'''

"f1=pd.read_csv('/content/processed_sensor_data_FD001.csv')\nf2=pd.read_csv('/content/processed_sensor_data_FD002.csv')\nf3=pd.read_csv('/content/processed_sensor_data_FD003.csv')\nf4=pd.read_csv('/content/processed_sensor_data_FD004.csv')"

In [3]:
#print(f2.head(3))

In [4]:
'''df=pd.concat([f1,f2,f3,f4])
df'''

'df=pd.concat([f1,f2,f3,f4])\ndf'

In [5]:
df=pd.read_csv('exports/processed/processed_sensor_data.csv')
df

,id,raw_id,source_file,engine_id,time_in_cycles,op_setting_1,op_setting_2,op_setting_3,s2,s3,...,rolling_std_s15,delta_s15,rolling_avg_s20,rolling_std_s20,delta_s20,rolling_avg_s21,rolling_std_s21,delta_s21,demo_rul,processed_at
0,1,1,FD001,1,1,-0.0007,-0.0004,100,641.82,1589.70,...,0.000000,0.0000,39.060000,0.000000,0.00,23.419000,0.000000,0.0000,191.0,2026-06-30 09:16:01.730864+00
1,2,2,FD001,1,2,0.0019,-0.0003,100,642.15,1591.82,...,0.008697,0.0123,39.030000,0.042426,-0.06,23.421300,0.003253,0.0046,190.0,2026-06-30 09:16:01.730864+00
2,3,3,FD001,1,3,-0.0043,0.0003,100,642.35,1587.99,...,0.007640,-0.0140,39.003333,0.055076,-0.05,23.395600,0.044573,-0.0794,189.0,2026-06-30 09:16:01.730864+00
3,4,4,FD001,1,4,0.0007,0.0000,100,642.35,1582.79,...,0.028117,-0.0496,38.972500,0.076322,-0.07,23.390175,0.037977,0.0297,188.0,2026-06-30 09:16:01.730864+00
4,5,5,FD001,1,5,-0.0019,-0.0002,100,642.37,1582.85,...,0.025953,0.0612,38.958000,0.073621,0.02,23.393020,0.033498,0.0305,187.0,2026-06-30 09:16:01.730864+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93269,123616,123616,FD004,100,200,20.0067,0.7000,100,606.74,1481.36,...,0.700162,-1.6527,15.912000,5.236628,10.25,9.557420,3.125682,6.1870,61.0,2026-06-30 09:16:01.730864+00
93270,123617,123617,FD004,100,201,35.0024,0.8400,100,555.78,1365.47,...,0.701195,0.0817,15.854000,5.250012,-9.94,9.564480,3.124264,-5.7314,60.0,2026-06-30 09:16:01.730864+00
93271,123618,123618,FD004,100,202,10.0005,0.2500,100,604.96,1506.11,...,0.824932,-0.6442,18.642000,7.645500,13.88,11.250480,4.608759,8.2697,59.0,2026-06-30 09:16:01.730864+00
93272,123619,123619,FD004,100,203,20.0077,0.7000,100,606.98,1482.48,...,0.835839,0.5327,21.446000,6.444496,-4.01,12.920120,3.865211,-2.5961,58.0,2026-06-30 09:16:01.730864+00
93273,123620,123620,FD004,100,204,34.9994,0.8404,100,555.48,1358.51,...,0.271118,0.1120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93274 entries, 0 to 93273
Data columns (total 51 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               93274 non-null  int64
 1   raw_id           93274 non-null  int64
 2   source_file      93274 non-null  object
 3   engine_id        93274 non-null  int64
 4   time_in_cycles   93274 non-null  int64
 5   op_setting_1     93274 non-null  float64
 6   op_setting_2     93274 non-null  float64
 7   op_setting_3     93274 non-null  int64
 8   s2               93274 non-null  float64
 9   s3               93274 non-null  float64
 10  s4               93274 non-null  float64
 11  s7               93274 non-null  float64
 12  s8               93274 non-null  float64
 13  s9               93274 non-null  float64
 14  s11              93274 non-null  float64
 15  s12              93274 non-null  float64
 16  s13              93274 non-null  float64
 17  s14              93274 non-null  float64
 18  s15              93274 non-null  float64
 19  s17              93274 non-null  int64
 20  s20              93274 non-null  float64
 21  s21              93274 non-null  float64
 22  rolling_avg_s2   93274 non-null  float64
 23  rolling_std_s2   93274 non-null  float64
 24  delta_s2         93274 non-null  float64
 25  rolling_avg_s3   93274 non-null  float64
 26  rolling_std_s3   93274 non-null  float64
 27  delta_s3         93273 non-null  float64
 28  rolling_avg_s4   93273 non-null  float64
 29  rolling_std_s4   93273 non-null  float64
 30  delta_s4         93273 non-null  float64
 31  rolling_avg_s7   93273 non-null  float64
 32  rolling_std_s7   93273 non-null  float64
 33  delta_s7         93273 non-null  float64
 34  rolling_avg_s11  93273 non-null  float64
 35  rolling_std_s11  93273 non-null  float64
 36  delta_s11        93273 non-null  float64
 37  rolling_avg_s12  93273 non-null  float64
 38  rolling_std_s12  93273 non-null  float64
 39  delta_s12        93273 non-null  float64
 40  rolling_avg_s15  93273 non-null  float64
 41  rolling_std_s15  93273 non-null  float64
 42  delta_s15        93273 non-null  float64
 43  rolling_avg_s20  93272 non-null  float64
 44  rolling_std_s20  93272 non-null  float64
 45  delta_s20        93272 non-null  float64
 46  rolling_avg_s21  93272 non-null  float64
 47  rolling_std_s21  93272 non-null  float64
 48  delta_s21        93271 non-null  float64
 49  demo_rul         93271 non-null  float64
 50  processed_at     93271 non-null  object
dtypes: float64(43), int64(6), object(2)
memory usage: 36.3+ MB

In [7]:
df.describe()

,id,raw_id,engine_id,time_in_cycles,op_setting_1,op_setting_2,op_setting_3,s2,s3,s4,...,rolling_avg_s15,rolling_std_s15,delta_s15,rolling_avg_s20,rolling_std_s20,delta_s20,rolling_avg_s21,rolling_std_s21,delta_s21,demo_rul
count,93274.000000,93274.000000,93274.000000,93274.000000,93274.000000,93274.000000,93274.000000,93274.000000,93274.000000,93274.000000,...,93273.000000,93273.000000,93273.000000,93272.000000,93272.000000,93272.000000,93272.000000,93272.000000,93271.000000,93271.000000
mean,61966.757242,61966.757242,52.243734,122.069816,12.646485,0.301442,96.820550,609.313610,1499.287795,1299.437125,...,8.888974,0.364778,-0.000090,29.373916,4.962912,-0.005586,17.624288,2.977711,-0.003301,121.838010
std,40586.023821,40586.023821,30.973452,82.502677,16.061993,0.363513,10.819905,41.544147,114.955775,133.533361,...,0.513390,0.402759,0.769237,9.605058,5.157790,10.149149,5.763083,3.095135,6.089870,83.377539
min,1.000000,1.000000,1.000000,1.000000,-0.008700,-0.000600,60.000000,535.480000,1242.980000,1025.520000,...,8.211120,0.000000,-2.572000,10.420000,0.000000,-29.010000,6.202000,0.000000,-17.433900,0.000000
25%,23319.250000,23319.250000,25.000000,57.000000,0.000100,0.000000,100.000000,555.650000,1366.080000,1135.110000,...,8.425320,0.018820,-0.040300,20.508000,0.095131,-0.230000,12.303880,0.056544,-0.134400,56.000000
50%,75793.500000,75793.500000,51.000000,113.000000,0.002800,0.000500,100.000000,641.910000,1580.850000,1394.615000,...,8.811380,0.079918,0.000200,28.406000,2.293830,0.000000,17.049240,1.376274,-0.000300,112.000000
75%,100301.750000,100301.750000,79.000000,171.000000,25.003000,0.700000,100.000000,642.590000,1589.630000,1406.820000,...,9.307860,0.819209,0.041400,38.888000,10.211809,0.220000,23.332520,6.127956,0.130400,171.000000
max,123620.000000,123620.000000,120.000000,525.000000,42.008000,0.842000,100.000000,645.110000,1616.910000,1441.490000,...,10.925400,1.753483,2.574500,39.732000,20.194970,29.100000,23.838700,12.126528,17.512300,524.000000

In [8]:

y=(df['demo_rul']<15).astype(int)
y.groupby(y).count()

demo_rul
0    87079
1     6195
Name: demo_rul, dtype: int64

In [9]:
df['failure'] = (df['demo_rul'] <= 15).astype(int)

In [10]:
engines = df['engine_id'].dropna().unique()
np.random.seed(42)
np.random.shuffle(engines)

In [11]:
train_size = int(len(engines) * 0.7)
train_engines = engines[:train_size]
test_engines = engines[train_size:]

train_df = df[df['engine_id'].isin(train_engines)]
test_df = df[df['engine_id'].isin(test_engines)]

In [12]:
drop_cols = ['id', 'raw_id', 'source_file', 'processed_at', 'demo_rul','engine_id','failure']
x_train=train_df.drop(drop_cols, axis=1)
y_train=train_df['failure']
x_test=test_df.drop(drop_cols, axis=1)
y_test=test_df['failure']

In [13]:
test_df.columns

Index(['id', 'raw_id', 'source_file', 'engine_id', 'time_in_cycles',
       'op_setting_1', 'op_setting_2', 'op_setting_3', 's2', 's3', 's4', 's7',
       's8', 's9', 's11', 's12', 's13', 's14', 's15', 's17', 's20', 's21',
       'rolling_avg_s2', 'rolling_std_s2', 'delta_s2', 'rolling_avg_s3',
       'rolling_std_s3', 'delta_s3', 'rolling_avg_s4', 'rolling_std_s4',
       'delta_s4', 'rolling_avg_s7', 'rolling_std_s7', 'delta_s7',
       'rolling_avg_s11', 'rolling_std_s11', 'delta_s11', 'rolling_avg_s12',
       'rolling_std_s12', 'delta_s12', 'rolling_avg_s15', 'rolling_std_s15',
       'delta_s15', 'rolling_avg_s20', 'rolling_std_s20', 'delta_s20',
       'rolling_avg_s21', 'rolling_std_s21', 'delta_s21', 'demo_rul',
       'processed_at', 'failure'],
      dtype='object')

In [14]:
rf_model = RandomForestClassifier(random_state=42, n_estimators=100, n_jobs=-1)
rf_model.fit(x_train, y_train)
rf_preds = rf_model.predict(x_test)

In [15]:
xgb_model = XGBClassifier(random_state=42, eval_metric='logloss')
xgb_model.fit(x_train, y_train)
xgb_preds = xgb_model.predict(x_test)

In [16]:
metrics = {
    'Random Forest': {
        'Precision': precision_score(y_test, rf_preds),
        'Recall': recall_score(y_test, rf_preds),
        'Accuracy': accuracy_score(y_test, rf_preds)
    },
    'XGBoost': {
        'Precision': precision_score(y_test, xgb_preds),
        'Recall': recall_score(y_test, xgb_preds),
        'Accuracy': accuracy_score(y_test, xgb_preds)
    }
}

In [17]:
print(classification_report(y_test, rf_preds))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99     24009
           1       0.88      0.81      0.84      1824

    accuracy                           0.98     25833
   macro avg       0.93      0.90      0.91     25833
weighted avg       0.98      0.98      0.98     25833

In [18]:
print(classification_report(y_test, xgb_preds))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99     24009
           1       0.85      0.82      0.83      1824

    accuracy                           0.98     25833
   macro avg       0.92      0.90      0.91     25833
weighted avg       0.98      0.98      0.98     25833

In [20]:
import joblib
joblib.dump(xgb_model, 'xgboost_predictive_model.pkl')

['xgboost_predictive_model.pkl']